[package]
name = "semsimian_server"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "semsimian_server"
path = "src/lib.rs"

[[bin]]
name = "semserver"
path = "src/bin.rs"

[dependencies]
semsimian = "=0.2.19"
rocket = { version = "0.5.1", features = ["json"] }
serde = "*"
chrono = ">=0.4.41"
lazy_static = { version = ">=1.4.0", features = [] }
