[package]
name = "semsimian_server"
description = "A server for SemSimian, a semantic similarity service for biomedical ontologies"
version = "0.2.2"
edition = "2024"
homepage = "https://github.com/monarch-initiative/semsimian-server"
repository = "https://github.com/monarch-initiative/semsimian-server"
readme = "README.md"
license = "BSD-3-Clause"
authors = ["Glass Ships <glass.ships@protonmail.com"]

[dependencies]
semsimian = "=0.2.19"
clap = { version = "4.5.40", features = ["derive"] }
lazy_static = { version = ">=1.5.0", features = [] }
rocket = { version = "0.5.1", features = ["json"] }
serde = ">=1.0.219"
# For downloading phenio
reqwest = { version = ">=0.12.22", features = ["blocking"] }
flate2 = "1.1.2"
tar = "0.4.44"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "semsimian_server"
path = "src/lib.rs"

[[bin]]
name = "semserver"
path = "src/bin.rs"
